name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Check
      run: |
        TARGET=build/libs/lanterna-sample-all.jar
        ls -laF ${TARGET}
        file ${TARGET} | grep archive
        md5sum ${TARGET}
